### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [jusss/BluetoothConnect#2]
I just downloaded the APK from your latest release (v2.8), and it identifies as

    package: name='com.example.bluetoothconnect' versionCode='1' versionName='1.0'

This is unexpected, expected was something like

    package: name='com.example.bluetoothconnect' versionCode='17' versionName='2.8'

(17 or higher as there were 16 other releases before it). Android uses `versionCode` internally to tell versions apart. Using always the same values makes updates hard at best. Could you please take care to [adjust the two](https://github.com/jusss/BluetoothConnect/blob/main/app/build.gradle#L14) whenever making a new release, so `versionName` matches what your tag suggests and `versionCode` is always increased?

While on it: some screenshots would be nice. A suggestion for such app metadata (description, graphics) is using Fastlane (see my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688)), which is what most Android apps use for that nowadays.

Thanks in advance!

**Comment by jusss** [comment]
thanks for your feedback, those adjustment have been made.

**Comment by IzzySoft** [comment]
Thanks! Looks fine :smiley:

So with the next sync around 7 pm UTC, your app [will become available in my repo](https://apt.izzysoft.de/packages/com.example.bluetoothconnect/). If you need adjustments to the app description there (or have some graphics to add, like icon or screenshots), just let me know. Especially a dedicated icon would probably be nice, as currently your app uses the default "green Andy" for that.

![image](https://github.com/jusss/BluetoothConnect/assets/6781438/a39d3f95-212c-4464-8bd6-7a334230c106)

Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link there e.g. from your Readme :smile:
